version: "3.1"

services:
  mosquitto:
    image: eclipse-mosquitto:1.6
    hostname: mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: always
    volumes:
      - mosquitto-storage:/mosquitto/data
    networks:
      - proxynet

volumes:
  mosquitto-storage:

networks:
  proxynet:
    name: kinetic-diamond-network
